export type Role = 'Customer' | 'Driver' | 'Admin';

export type Screen =
  // Customer
  | 'Welcome'
  | 'Login'
  | 'Register'
  | 'ForgotPassword'
  | 'OTPVerification'
  | 'LivePhotoLogin'
  | 'PostLoginVerification'
  | 'ServiceSelection'
  | 'TripDetailsInput'
  | 'ScheduleRide'
  | 'CarRental'
  | 'AvailableCarsForRent'
  | 'CarRentDetails'
  | 'CarRentalConfirmation'
  | 'AvailableShuttles'
  | 'CompatibleShuttlesList'
  | 'ShuttleDriverDetails'
  | 'BookingConfirmation'
  | 'PaymentSelection'
  | 'PaymentProcessing'
  | 'TripTracking'
  | 'TripCompletionReceipt'
  | 'TripHistory'
  | 'TripDetailsView'
  | 'MyBookings'
  | 'MyBookingsInstant'
  | 'MyBookingsSchedule'
  | 'MyBookingsRental'
  | 'AccountProfile'
  | 'SavedPassengers'
  | 'EmergencyContacts'
  | 'StartCarReservation'
  | 'ManageReservation'
  | 'DealsAndCoupons'
  | 'GetReceipt'
  | 'OneWayRental'
  | 'LongTermRental'
  | 'BusinessSolutions'
  | 'Hospitality'
  | 'Sitemap'
  // Driver
  | 'DriverLogin'
  | 'DriverPasswordRecovery'
  | 'DriverRegistration'
  | 'DocumentUpload'
  | 'DriverDashboard'
  | 'ApplicationStatus'
  | 'TripRequest'
  | 'TripManagement'
  | 'DriverTripCompletion'
  | 'EarningsDashboard'
  // Admin
  | 'AdminLogin'
  | 'AdminPasswordRecovery'
  | 'AdminDashboard'
  | 'DriverManagement'
  | 'LiveOperations'
  | 'AdminBookings'
  | 'SystemConfig';
  
export interface NavigationProps {
    navigate: (screen: Screen, view?: string) => void;
    logout?: () => void;
}
